name: Publish to NPM
on:
  release:
    types: [released]

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17.x
          registry-url: https://registry.npmjs.org
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno task build:npm
      - run: npm publish --access=public
        working-directory: tmp/npm/wrp
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm publish --access=public
        working-directory: tmp/npm/wrp-react
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm publish --access=public
        working-directory: tmp/npm/wrp-jotai
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
